apiVersion: v1
kind: Service
metadata:
  name: maeno-backend-service
  namespace: maeno-fe
spec:
  type: ExternalName
  externalName: maeno-backend-service.maeno-be.svc.cluster.local
  selector:
    role: maeno-backend-webserver 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
