apiVersion: apps/v1
kind: Deployment
metadata:
  name: maeno-frontend
  namespace: maeno-fe
  labels:
    role: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      role: maeno-frontend-webserver
  template:
    metadata:
      labels:
        role: maeno-frontend-webserver
    spec:
      containers:
      - name: webserver
        imagePullPolicy: Always
        image: kshithija/maeno-fe:v1.0.1
        lifecycle:
          postStart:
            exec:
              command:
                - bin/bash
                - -c
                - curl http://maeno-backend-service.maeno-be.svc.cluster.local:3000/seed > /tmp/seed.txt 
