name: Dispacher Reciver

on:
  workflow_dispatch:
    inputs:
      version_id:
        description: 'updated version'
        required: true
        
concurrency:
  group: FE-Deployment
  
jobs:
  id:
    name: Workflow ID Provider
    runs-on: self-hosted
    steps:
      - name: ${{github.event.inputs.version_id}}
        run: echo run identifier ${{ inputs.version_id }}
        
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Location
        run: pwd
          
      - name: update the version
        run: "sed -i -E \"s/image: kshithija\/maeno-fe:v[0-9]+.[0-9]+.[0-9]+/image: kshithija\/maeno-fe:${{ inputs.version_id }}/g\" ./infra-code/maeno-fe.yaml"
        
      - name: Commit version update
        run: |
          git commit -am "Automated version update"
          git push origin main
          
      - name: deploy
        run: "kubectl apply -f ./infra-code -R"
