name: Dispacher Reciver

on:
  workflow_dispatch:
    inputs:
      version_id:
        description: 'run identifier'
        required: false
jobs:
  id:
    name: Workflow ID Provider
    runs-on: self-hosted
    steps:
      - name: ${{github.event.inputs.version_id}}
        run: echo run identifier ${{ inputs.version_id }}
        
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
