name: Frontend Dispacher Reciver

on:
  workflow_dispatch:
    inputs:
      version_id:
        description: 'updated version'
        required: true
        
concurrency:
  group: Deployment
  
jobs:
  id:
    name: Deploy to production
    runs-on: self-hosted
    steps:
        
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Location
        run: pwd
          
      - name: update the version
        env:
          VERSION: ${{github.event.inputs.version_id}}
        run: "sed -i -E \"s/image: kshithija\\/maeno-fe:v[0-9]+\\.[0-9]+\\.[0-9]+/image: kshithija\\/maeno-fe:$VERSION/g\" ./infra-code/maeno-fe-deployment.yaml"
        
      - name: Commit version update
        run: |
          test -z "$(git diff-index --name-only HEAD --)" || git commit -am "Automated version update"
          git push origin main
          
      - name: deploy
        run: "kubectl apply -f ./infra-code -R"
          
      - name: Build artifacts
        run: zip -r maeno-infra.zip .
        
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: maeno-infra-fe-${{github.event.inputs.version_id}}
          tag_name: fe-${{github.event.inputs.version_id}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./maeno-infra.zip
          asset_name: maeno-infra.zip
          asset_content_type: application/zip
