name: Dispatcher

on:
  push:
    branches:
      - main

concurrency:
  group: Deployment

jobs:
  build_release:
    name: build_release
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Version
        run: echo "::set-output name=version::$(cat version | cut -d ':' -f2 | awk '{$1=$1};1')"
        id: version

      - name: deploy
        run: "kubectl apply -f ./infra-code -R"
        
      - name: Build artifacts
        run: zip -r maeno-infra.zip .
        
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: maeno-infra-${{ steps.version.outputs.version }}
          tag_name: infra-${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./maeno-infra.zip
          asset_name: maeno-infra.zip
          asset_content_type: application/zip
